version: '2'


services:
  db:
    image: postgres:15.4-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data

  django:
    build: .
    environment:
      - DEBUG=True
    tmpfs: /tmp
    depends_on:
      - "db"
    links:
      - "db"

  nginx:
    build: .
    depends_on:
      - "django"
    links:
      - "django:django"
    command: nginx
    ports:
      - "80:80/tcp"


volumes:
  db:
    driver: local
